/**
 * Nanryosai 2026
 * Version: 0.1.0
 * Last Modified: 2026-02-05
 * Author: Nanryosai 2026 Project Team
 *
 * 2025年度南陵祭 公式企画データ（過去資料）
 */

// 企画の名簿データ
const projectData = [
  // --- 4階 ---
  {
    id: "1-1",
    name: "1年1組「タケムランド」",
    catchphrase: "人生変えませんか?",
    place: "4階",
    floor: 4,
    mapX: 160,
    mapY: 833,
    tags: ["1年生", "体験・ゲーム"],
    description: "カジノへようこそ!	<br>安心してください、破産しません。",
    image: "images/ira/1-1.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "1-2",
    name: "1年2組「赤字のカジノ ~ちょっぴり大人な休憩所~」",
    catchphrase: "赤字ですたすけて！",
    place: "4階",
    floor: 4,
    mapX: 362,
    mapY: 833,
    tags: ["1年生", "体験・ゲーム"],
    description:
      "チンチロ、ポーカー、ブラックジャック、限界しりとりができます！<br>遊んでお菓子GET！！",
    image: "images/main/1-2.jpg",
    contentType: "gallery",
    gallery: ["images/gallery/1-2-1.jpg", "images/gallery/1-2-2.jpg"],
  },
  {
    id: "1-3",
    name: "1年3組「中村縁日 ~射的でストレス発散~」",
    catchphrase: "射的でストレス発散しましょう",
    place: "4階",
    floor: 4,
    mapX: 574,
    mapY: 833,
    tags: ["1年生", "体験・ゲーム"],
    description:
      "何発か当てるとお菓子が貰えるかも??<br>本物の屋台で使われる銃を使用しておりなんと一丁2万5000円!!!<br>文化祭で体験できるのはここのみ！",
    image: "images/ira/1-3.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "1-4",
    name: "1年4組「あの子はどこ? ~次々といなくなる不可解な事件~」",
    catchphrase: "一番怖いお化け屋敷",
    place: "4階",
    floor: 4,
    mapX: 784,
    mapY: 833,
    tags: ["1年生", "お化け屋敷"],
    description: "南陵一怖いお化け屋敷へようこそ",
    image: "images/ira/1-4.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "1-5",
    name: "1年5組「メイド喫茶ひさし」",
    catchphrase: "",
    place: "4階",
    floor: 4,
    mapX: 998,
    mapY: 833,
    tags: ["1年生", "カフェ"],
    description: "",
    image: "images/ira/1-5.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "1-6",
    name: "1年6組「前園のハッピーライド」",
    catchphrase: "回ったっていいじゃん!",
    place: "4階",
    floor: 4,
    mapX: 2034,
    mapY: 833,
    tags: ["1年生", "体験・ゲーム"],
    description: "モンスタースイング仕様のコーヒーカップに乗れます!!!",
    image: "images/edited/1-6.png",
    contentType: "gallery",
    gallery: ["images/gallery/1-6-1.jpg", "images/gallery/1-6-2.jpg"],
  },
  {
    id: "1-7",
    name: "1年7組「MADE in MENDY」",
    catchphrase: "来た人全員にラブ注入します ;",
    place: "4階",
    floor: 4,
    mapX: 2240,
    mapY: 833,
    tags: ["1年生", "カフェ"],
    description:
      "店に入るとメイドや執事が席に案内してくれて色々なおもてなしをしてくれます!!!",
    image: "images/ira/1-7.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "election-corner",
    name: "選挙コーナー「選挙の投票体験」",
    catchphrase: "",
    place: "4階 選択教室1",
    locationId: "ec1",
    floor: 4,
    mapX: 1823,
    mapY: 833,
    tags: ["その他"],
    description: "",
    image: "images/no.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "megumi",
    name: "横田めぐみさん「拉致被害者 横田めぐみさんに関する展示」",
    catchphrase: "",
    place: "4階 選択教室1",
    locationId: "ec1",
    tags: ["その他", "展示"],
    description: "",
    image: "images/no.jpg",
    contentType: "gallery",
    gallery: [],
  },

  // --- 3階 ---
  {
    id: "2-1",
    name: "2年1組「13年前の校舎」",
    catchphrase: "あなたは教室の謎を解明できるか",
    place: "3階",
    floor: 3,
    mapX: 162,
    mapY: 833,
    tags: ["2年生", "お化け屋敷"],
    description:
      "13年前、2年1組の教室で36番の子が突然行方不明になりました。<br>手がかりは教室内に散らばっており、皆様に探して、持ってきてもらいます。<br>もしかしたら36番目の子とあってしまうかも...<br>ぜひ2年1組に来てください。",
    image: "images/ira/2-1.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "2-2",
    name: "2年2組「ROUND2」",
    catchphrase: "的に夢中青春ストライク！",
    place: "3階",
    floor: 3,
    mapX: 372,
    mapY: 833,
    tags: ["2年生", "体験・ゲーム"],
    description: "ダーツが楽しい",
    image: "images/ira/2-2.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "2-3",
    name: "2年3組「ボードゲームカフェ ~SUGURU~」",
    catchphrase: "",
    place: "3階",
    floor: 3,
    mapX: 573,
    mapY: 833,
    tags: ["2年生", "カフェ"],
    description: "",
    image: "images/main/2-3.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "2-4",
    name: "2年4組「Club楓」",
    catchphrase: "",
    place: "3階",
    floor: 3,
    mapX: 788,
    mapY: 833,
    tags: ["2年生", "カフェ"],
    description:
      "お菓子や飲み物を販売しています。<br>お客さん自身が売っているもので組み合わせてカスタマイズできるようになっています!<br>come on!!",
    image: "images/ira/2-4.jpg",
    contentType: "menu",
    menu: [
      { name: "三ツ矢サイダー", price: "80円", desc: "" },
      { name: "オレンジジュース", price: "70円", desc: "" },
      { name: "カルピス", price: "80円", desc: "" },
      { name: "コーラ", price: "60円", desc: "" },
      { name: "ミルクティー", price: "50円", desc: "" },
      { name: "パチパチパニック", price: "40円", desc: "" },
      { name: "わたあめ", price: "80円", desc: "" },
      { name: "ソーダアイス", price: "60円", desc: "" },
      { name: "カルパス", price: "おまけ", desc: "" },
    ],
  },
  {
    id: "2-5",
    name: "2年5組「純喫茶ナオヤとヒカル兄やん。」",
    catchphrase: "昭和レトロで一服しよっ",
    place: "3階",
    floor: 3,
    mapX: 992,
    mapY: 833,
    tags: ["2年生", "カフェ"],
    description: "レトロをテーマにしたカフェでプリンとかラムネがあります！",
    image: "images/main/2-5.jpg",
    contentType: "menu",
    menu: [
      { name: "プリン", desc: "", price: "100円" },
      { name: "ラムネ", desc: "", price: "100円" },
      { name: "メロンソーダ", desc: "", price: "100円" },
      { name: "オレンジジュース", desc: "", price: "100円" },
    ],
    gallery: [
      "images/gallery/2-5.jpg",
      "images/gallery/2-5-2.jpg",
      "images/gallery/2-5-3.jpg",
      "images/gallery/2-5-4.jpg",
    ],
  },
  {
    id: "2-6",
    name: "2年6組「ナベ病院 ~開かずの診察室~」",
    catchphrase: "文化祭で体験する廃病院",
    place: "3階",
    floor: 3,
    mapX: 1611,
    mapY: 833,
    tags: ["2年生", "お化け屋敷"],
    description:
      "2年6組にある廃病院の中から数字を見つけ出して脱出してもらいます！",
    image: "images/ira/2-6.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "2-7",
    name: "2年7組「?Melty めいど?」",
    catchphrase: "チョコミントよりもあなた??",
    place: "3階",
    floor: 3,
    mapX: 1816,
    mapY: 833,
    tags: ["2年生", "カフェ"],
    description: "ドキドキさせる時間をお届けします??",
    image: "images/ira/2-7.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "biology-club",
    name: "生物部「生物部」",
    catchphrase: "",
    place: "3階 生物室",
    floor: 3,
    mapX: 162,
    mapY: 1431,
    tags: ["部活動・同好会", "展示"],
    description: "",
    image: "images/ira/生物部.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "art-club",
    name: "美術部「展示発表会」",
    catchphrase: "美術of美術",
    place: "3階 美術室",
    floor: 3,
    mapX: 1757,
    mapY: 1292,
    locationId: "art-room",
    tags: ["部活動・同好会", "展示"],
    description:
      "一筆の線、一滴の色彩。<br>重なり合って生まれるのは、私たちだけの景色。<br>美術部の世界へようこそ。",
    image: "images/main/美術部.jpg",
    contentType: "gallery",
    gallery: ["images/gallery/bijyutubu1.jpg", "images/gallery/bijyutubu2.jpg"],
  },
  {
    id: "art-course",
    name: "美術科「美術科 授業制作作品展示」",
    catchphrase: "",
    place: "3階 美術室",
    floor: 3,
    locationId: "art-room",
    tags: ["その他", "展示"],
    description: "",
    image: "images/no.jpg",
    contentType: "gallery",
    gallery: [],
  },

  // --- 2階 ---
  {
    id: "game-club-room",
    name: "ゲーム同好会「威超頂点杯（南陵スマブラ大会）」",
    catchphrase: "南陵一のスマブラプレイヤーは誰だ",
    place: "2階 3-3教室",
    floor: 2,
    mapX: 573,
    mapY: 833,
    time: "11:00-",
    tags: ["部活動・同好会", "体験・ゲーム"],
    description:
      "南陵生徒、教師でNo.1スマブラプレイヤーを決めるトーナメント。<br>DAY1に3-3教室で予選、DAY2に体育館で決勝戦を行います！",
    image: "images/main/ゲーム同好会.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "tea-ceremony-club",
    name: "茶道部「夏果の茶会~ふらっと茶縁日和~」",
    catchphrase: "一茶入魂",
    place: "2階",
    floor: 2,
    mapX: 2271,
    mapY: 867,
    tags: ["部活動・同好会", "カフェ"],
    description:
      "心を込めて作り上げるお抹茶と美しい和菓子を提供し、皆様に癒しのひとときを提供します",
    image: "images/main/茶道部.png",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "literature-club",
    name: "文芸同好会「丸い鈴に隠された物語 ~あらすじを辿って~」",
    catchphrase: "",
    place: "2階",
    floor: 2,
    mapX: 783,
    mapY: 833,
    tags: ["部活動・同好会", "展示"],
    description: "",
    image: "images/ira/文芸部.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "manga-club",
    name: "漫画研究部「The future day break」",
    catchphrase: "",
    place: "2階",
    floor: 2,
    mapX: 998,
    mapY: 833,
    tags: ["部活動・同好会", "展示"],
    description: "",
    image: "images/ira/マンガ研究会.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "disaster-prevention-committee",
    name: "防災委員会「高めよう防災意識」",
    catchphrase: "",
    place: "2階廊下",
    floor: 2,
    mapX: 1492,
    mapY: 968,
    tags: ["委員会", "展示"],
    description: "",
    image: "images/ira/防災委員会.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "calligraphy-course",
    name: "書道科「書道展2025」",
    catchphrase: "",
    place: "2階 書道室",
    floor: 2,
    mapX: 1752,
    mapY: 1301,
    tags: ["その他", "展示"],
    description: "",
    image: "images/no.jpg",
    contentType: "gallery",
    gallery: [],
  },
  {
    id: "pta",
    name: "PTA「Nanryo Mart」",
    catchphrase: "あなたとコンビニ、南陵マート",
    place: "2階",
    floor: 2,
    mapX: 366,
    mapY: 833,
    tags: ["その他", "販売"],
    description: "ドリンクやパン、お菓子を販売??",
    image: "images/ira/PTA.jpg",
    contentType: "gallery",
    gallery: [],
  },

  // --- 5階 ---
  {
    id: "library-committee",
    name: "図書委員会「天球の図書館」",
    catchphrase: "",
    place: "5階 図書館",
    floor: 5,
    mapX: 2235,
    mapY: 874,
    tags: ["委員会", "展示"],
    description: "",
    image: "images/ira/図書委員会.jpg",
    contentType: "gallery",
    gallery: [],
  },

  // --- 外/ピロティ/昇降口など (便宜上1階として扱います) ---
  {
    id: "3-1-food",
    name: "3年1組「フランクフルト」",
    catchphrase: "かおりに誘われて...ひとくちの幸せ",
    place: "外テント",
    floor: 1,
    mapX: 367,
    mapY: 1238,
    tags: ["3年生", "販売"],
    description: "食べ歩きにぴったり!<br>文化祭限定の味を楽しもう!",
    image: "images/ira/3-1.jpg",
    contentType: "menu",
    menu: [
      { name: "フランクフルト", desc: "", price: "70円" },
      { name: "ホットドック", desc: "", price: "100円" },
    ],
  },
  {
    id: "3-2-food",
    name: "3年2組「たこってかない?」",
    catchphrase: "",
    place: "外テント",
    floor: 1,
    mapX: 367,
    mapY: 1128,
    tags: ["3年生", "販売"],
    description: "",
    image: "images/main/3-2.jpg",
    contentType: "menu",
    menu: [],
    gallery: [
      "images/gallery/3-2-1.jpg",
      "images/gallery/3-2-2.jpg",
      "images/gallery/3-2-3.jpg",
    ],
  },
  {
    id: "3-3-food",
    name: "3年3組「ケバブ」",
    catchphrase: "",
    place: "外テント",
    floor: 1,
    mapX: 2124,
    mapY: 1452,
    tags: ["3年生", "販売"],
    description: "",
    image: "images/main/3-3.jpg",
    contentType: "menu",
    menu: [],
    gallery: ["images/gallery/3-3-1.jpg"],
  },
  {
    id: "3-4-food",
    name: "3年4組「やきとり」",
    catchphrase: "",
    place: "外テント",
    floor: 1,
    mapX: 367,
    mapY: 1348,
    tags: ["3年生", "販売"],
    description: "",
    image: "images/ira/3-4.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "3-5-food",
    name: "3年5組「畠山が認めた三ツ星炭火焼き店」",
    catchphrase: "",
    place: "外テント",
    floor: 1,
    mapX: 2124,
    mapY: 1550,
    tags: ["3年生", "販売"],
    description: "",
    image: "images/ira/3-5.jpg",
    contentType: "menu",
    menu: [],
  },
  {
    id: "3-6-food",
    name: "3年6組「そばにいて。」",
    catchphrase: "浅野屋より焼きそばの提供",
    place: "外テント",
    floor: 1,
    mapX: 2124,
    mapY: 1350,
    tags: ["3年生", "販売"],
    description: "がっつりソース焼きそば",
    image: "images/main/3-6.jpg",
    contentType: "menu",
    menu: [{ name: "焼きそば", desc: "がっつり焼きそば", price: "180円" }],
  },
  {
    id: "3-7-food",
    name: "3年7組「豚串こみちゃん」",
    catchphrase: "タン串がなななんと150円！！",
    place: "外テント",
    floor: 1,
    mapX: 598,
    mapY: 1128,
    tags: ["3年生", "販売"],
    description:
      "私たち3年7組は豚串とタン串を販売しています。<br>味は塩、タレとレモン汁はお好みで付けられます。<br>タン串は1日100本限定なので是非来てください！",
    image: "images/gallery/3-7-1.jpg",
    contentType: "menu",
    gallery: [""],
    menu: [
      { name: "豚バラ串", desc: "", price: "100円" },
      { name: "タン串", desc: "", price: "150円" },
    ],
  },
  {
    id: "home-making-club",
    name: "ホームメイキング部「手作りお菓子の販売」",
    catchphrase: "おいしいスコーンはいかが？",
    place: "ピロティ(外)",
    floor: 1,
    mapX: 1993,
    mapY: 879,
    tags: ["部活動・同好会", "販売"],
    description:
      "ホームメイキング部手作りの4種類のスコーンを販売します!!<br>味は「抹茶」「ココア」「紅茶」「塩」全品100円<br>校門入って右曲がってまっすぐ行った先のピロティで販売するので、ぜひ食べてみてはいかがでしょうか…？",
    image: "images/ira/ホームメイキング部.jpg",
    contentType: "menu",
    menu: [
      {
        name: "スコーン(抹茶味)",
        desc: "程よい甘みの中に感じる抹茶がとても良い…。",
        price: "100円",
      },
      {
        name: "スコーン(ココア味)",
        desc: "定番のココア…！ちょうどよい甘みが口の中でとろける…。",
        price: "100円",
      },
      {
        name: "スコーン(紅茶味)",
        desc: "ほんのり甘くて、紅茶の香りで満たされる…！",
        price: "100円",
      },
      {
        name: "スコーン(塩味)",
        desc: "甘いのが苦手な人でも食べられる、いい塩加減がやみつきになる！",
        price: "100円",
      },
    ],
  },
];

// =======================================================
// ★★★ ステージ発表のデータ (シンプル版・完成形) ★★★
// =======================================================
const stageData = [
  // --- DAY 1 ---
  {
    id: "day1-keion-1",
    groupId: "keion",
    groupName: "軽音楽部",
    name: "ライブ",
    place: "体育館",
    locationId: "gymnasium",
    time: "10:30 - 11:20",
    tags: ["DAY1", "ステージ", "音楽", "部活動"],
    groupDescription:
      "私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！",
    image: "images/group-keion.jpg",
  },
  {
    id: "day1-shafuku",
    groupId: "shafuku",
    groupName: "社会福祉部",
    name: "発表",
    place: "体育館",
    locationId: "gymnasium",
    time: "11:45 - 12:05",
    tags: ["DAY1", "ステージ", "発表", "部活動"],
    groupDescription:
      "社会福祉部の活動について発表します。私たちの取り組みをぜひご覧ください。",
    image: "images/group-shafuku.jpg",
  },
  {
    id: "day1-keion-2",
    groupId: "keion",
    groupName: "軽音楽部",
    name: "ライブ",
    place: "3階視聴覚室",
    locationId: "av-room",
    time: "12:00 - 15:00",
    tags: ["DAY1", "ステージ", "音楽", "部活動"],
    groupDescription:
      "私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！",
    image: "images/group-keion.jpg",
  },
  {
    id: "day1-danbasu",
    groupId: "danbasu",
    groupName: "男子バスケ部",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "12:20 - 12:45",
    tags: ["DAY1", "ステージ", "パフォーマンス", "部活動"],
    groupDescription:
      "男子バスケットボール部が、コートを離れてステージでスペシャルパフォーマンスを披露します！お楽しみに！",
    image: "images/group-danbasu.jpg",
  },
  {
    id: "day1-gunma",
    groupId: "gunma",
    groupName: "ぐんまさ",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "13:10 - 13:20",
    tags: ["DAY1", "ステージ", "パフォーマンス", "有志"],
    groupDescription:
      "有志団体「ぐんまさ」によるスペシャルパフォーマンスです！",
    image: "images/group-yushi.jpg",
  },
  {
    id: "day1-aomito-1",
    groupId: "aomito",
    groupName: "あおみとnumber〜",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "13:30 - 13:40",
    tags: ["DAY1", "ステージ", "パフォーマンス", "有志"],
    groupDescription: "",
    image: "images/main/あおみとnumber.jpg",
  },
  {
    id: "day1-suibu",
    groupId: "suibu",
    groupName: "吹奏楽部",
    name: "コンサート",
    place: "4階 音楽室",
    locationId: "music-room",
    time: "13:30 - 14:15",
    tags: ["DAY1", "ステージ", "音楽", "部活動"],
    groupDescription:
      "吹奏楽部によるミニコンサートです。両日とも音楽室で開催します。美しいハーモニーをお楽しみください。",
    image: "images/ira/吹奏楽部.jpg",
  },
  {
    id: "day1-modern-dance",
    groupId: "moderndance",
    groupName: "モダンダンス部",
    name: "ダンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "14:10 - 15:00",
    tags: ["DAY1", "ステージ", "ダンス", "部活動"],
    groupDescription:
      "モダンダンス部による情熱的なパフォーマンスにご期待ください。両日とも体育館で発表します！",
    image: "images/group-moderndance.jpg",
  },

  // --- DAY 2 ---
  {
    id: "day2-soukyoku",
    groupId: "soukyoku",
    groupName: "箏曲部",
    name: "演奏会",
    place: "体育館",
    locationId: "gymnasium",
    time: "10:30 - 11:00",
    tags: ["DAY2", "ステージ", "音楽", "部活動"],
    groupDescription: "箏曲部による、和の美しい音色をお楽しみください。",
    image: "images/group-soukyoku.jpg",
  },
  {
    id: "day2-keion-3",
    groupId: "keion",
    groupName: "軽音楽部",
    name: "ライブ",
    place: "3階視聴覚室",
    locationId: "av-room",
    time: "10:00 - 13:00",
    tags: ["DAY2", "ステージ", "音楽", "部活動"],
    groupDescription:
      "私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！",
    image: "images/group-keion.jpg",
  },
  {
    id: "day2-danbasu",
    groupId: "danbasu",
    groupName: "男子バスケ部",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "11:00 - 11:25",
    tags: ["DAY2", "ステージ", "パフォーマンス", "部活動"],
    groupDescription:
      "男子バスケットボール部が、コートを離れてステージでスペシャルパフォーマンスを披露します！お楽しみに！",
    image: "images/group-danbasu.jpg",
  },
  {
    id: "day2-game",
    groupId: "game",
    groupName: "ゲーム同好会「威超頂点杯（南陵スマブラ大会）」",
    name: "大会",
    place: "体育館",
    locationId: "gymnasium",
    time: "11:25 - 11:40",
    tags: ["DAY2", "ステージ", "発表", "部活動"],
    groupDescription:
      "南陵生徒、教師でNo.1スマブラプレイヤーを決めるトーナメント。<br>DAY1に3-3教室で予選、DAY2に体育館で決勝戦を行います！",
    image: "images/main/ゲーム同好会.jpg",
  },
  {
    id: "day2-shafuku",
    groupId: "shafuku",
    groupName: "社会福祉部",
    name: "発表",
    place: "体育館",
    locationId: "gymnasium",
    time: "11:40 - 12:00",
    tags: ["DAY2", "ステージ", "発表", "部活動"],
    groupDescription:
      "社会福祉部の活動について発表します。私たちの取り組みをぜひご覧ください。",
    image: "images/group-shafuku.jpg",
  },
  {
    id: "day2-gunma",
    groupId: "gunma",
    groupName: "ぐんまさ",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "12:00 - 12:10",
    tags: ["DAY2", "ステージ", "パフォーマンス", "有志"],
    groupDescription:
      "有志団体「ぐんまさ」によるスペシャルパフォーマンスです！",
    image: "images/group-yushi.jpg",
  },
  {
    id: "day2-aomito-2",
    groupId: "aomito",
    groupName: "あおみと",
    name: "パフォーマンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "12:10 - 12:20",
    tags: ["DAY2", "ステージ", "パフォーマンス", "有志"],
    groupDescription:
      "有志団体「あおみと」によるスペシャルパフォーマンスです！",
    image: "images/group-yushi.jpg",
  },
  {
    id: "day2-dancingjk",
    groupId: "dancingjk",
    groupName: "ダンシングJK",
    name: "ダンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "12:20 - 13:00",
    tags: ["DAY2", "ステージ", "ダンス", "有志"],
    groupDescription:
      "有志団体「ダンシングJK」による、パワフルなダンスステージ！",
    image: "images/group-yushi.jpg",
  },
  {
    id: "day2-chorus",
    groupId: "chorus",
    groupName: "コーラス部",
    name: "コンサート",
    place: "4階 音楽室",
    locationId: "music-room",
    time: "12:30 - 13:30",
    tags: ["DAY2", "ステージ", "音楽", "部活動"],
    groupDescription:
      "コーラス部による美しい歌声が音楽室に響き渡ります。ぜひ聴きに来てください。",
    image: "images/group-chorus.jpg",
  },
  {
    id: "day2-modern-dance",
    groupId: "moderndance",
    groupName: "モダンダンス部",
    name: "ダンス",
    place: "体育館",
    locationId: "gymnasium",
    time: "13:00 - 13:50",
    tags: ["DAY2", "ステージ", "ダンス", "部活動"],
    groupDescription:
      "モダンダンス部による情熱的なパフォーマンスにご期待ください。両日とも体育館で発表します！",
    image: "images/group-moderndance.jpg",
  },
  {
    id: "day2-suibu",
    groupId: "suibu",
    groupName: "吹奏楽部",
    name: "コンサート",
    place: "4階 音楽室",
    locationId: "music-room",
    time: "13:30 - 14:15",
    tags: ["DAY2", "ステージ", "音楽", "部活動"],
    groupDescription:
      "吹奏楽部によるミニコンサートです。両日とも音楽室で開催します。美しいハーモニーをお楽しみください。",
    image: "images/group-suibu.jpg",
  },
  {
    id: "day2-keion-4",
    groupId: "keion",
    groupName: "軽音楽部",
    name: "ライブ",
    place: "体育館",
    locationId: "gymnasium",
    time: "14:10 - 15:00",
    tags: ["DAY2", "ステージ", "音楽", "部活動"],
    groupDescription:
      "私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！",
    image: "images/group-keion.jpg",
  },
  // --- 以下は場所の情報なので、変更なし ---
  {
    id: "place-gym",
    name: "体育館ステージ",
    place: "体育館",
    locationId: "gymnasium",
    hubType: "primary",
    floor: 1,
    mapX: 1014,
    mapY: 1327,
    catchphrase: "文化祭のメインステージ！",
    description:
      "熱いパフォーマンスが繰り広げられるメインステージです。タイムテーブルをチェック！",
    tags: ["ステージ", "ステージ"],
    image: "images/gym-stage.jpg",
  },
  {
    id: "place-av-room",
    name: "視聴覚室ライブ",
    place: "3階 視聴覚室",
    locationId: "av-room",
    floor: 3,
    mapX: 1300,
    mapY: 570,
    hubType: "secondary",
    catchphrase: "ライブハウスはこちら！",
    description:
      "熱いライブが繰り広げられるサブステージです。タイムテーブルをチェック！",
    tags: ["ステージ"],
    image: "images/av-room.jpg",
  },
  {
    id: "place-music-room",
    name: "音楽室コンサート",
    place: "4階 音楽室",
    locationId: "music-room",
    floor: 4,
    mapX: 1752,
    mapY: 1300,
    hubType: "secondary",
    catchphrase: "美しい音色が響き渡る。",
    tags: ["ステージ"],
    image: "images/music-room.jpg",
  },
];
